# Build settings
# Gems
gems: 
- jekyll-paginate
- jekyll-feed

# url is the full website URL
# baseurl is the website's URL without the hostname
# If you are hosting it on Github for some project with name 'projectname', then the url and baseurl should look like:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"
url: ""
enforce_ssl: ""
baseurl: "/jekyllBasic"

# Title of website
title: Project Name

#Default keywords (used if no keywords are specified on a page basis)
keywords: test1, test2, etc

# Short description of your site
desc: Sample Description

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar.jpg"

# List of links in the navigation bar
nav-links:
  Home: ""
  About Me: "aboutme"
  Contact: "contact"  
  
# --- Footer options --- #

# If the values are empty, they are ignored 
profile:
  name: Babji Chetty
  email: Your-Email
  facebook: your-fb-id
  github: your-github-id 
  twitter: your-twitter-id
  linkedin: your-linkedin-id
  stackoverflow: your-stackoverflow-id

# To display link in the footer section
pretty-url: "bchetty.com"

# --- Misc --- #

# Your Disqus profile (shortname) settings
disqus: "Your-Disqus-Id"

# Google Analytics Settings
google_analytics: "Your-GA-Id"

# Set these options as you need (For more information, check Jekyll's site)
timezone: "Europe/Berlin"
markdown: kramdown
highlighter: rouge
permalink: /blog/:title
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      show-avatar: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

created-by: Babji, Chetty
creator-url: https://bchetty.com